# Generated by Django 5.2.4 on 2025-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catename', models.CharField(blank=True, max_length=50, null=True)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='category_file')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
