# Generated by Django 5.2.4 on 2025-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_pro', models.CharField(blank=True, max_length=50, null=True)),
                ('proname', models.CharField(blank=True, max_length=50, null=True)),
                ('proimg', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('cost', models.IntegerField(blank=True, max_length=50, null=True)),
                ('pdesc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
