# Generated by Django 5.2.4 on 2025-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
