# Generated by Django 5.2.4 on 2025-08-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('u_password', models.CharField(blank=True, max_length=50, null=True)),
                ('c_password', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
