# Generated by Django 5.2.4 on 2025-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
