# Generated by Django 5.2.4 on 2025-08-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_cartdb_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
