# Generated by Django 5.2.4 on 2025-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_cartdb_price_alter_cartdb_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
